Sales Warrior/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales_Warrior.Controllers
{
    public class OrderDetailsController : Controller
    {
        // GET: OrderDetails
        public ActionResult Index()
        {
            return View();
        }
    }
}

Sales Warrior/Controllers/Order_DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales_Warrior.Controllers
{
    public class Order_DetailsController : Controller
    {
        // GET: Order_Details
        public ActionResult Order_Details()
        {
            return View();
        }
    }
}

Sales Warrior/Views/OrderDetails/Index.cshtml
@model Sales_Warrior.Order
<html>
<head>
    <style>
             table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
           
        }

        .form-element-row label {
            display: inline-block;
            width: 125px;
        }

        .form-element-row input {
            width: 350px;
        }
        <meta charset="utf-8" >
        <meta name="viewport" content="width=device-width, initial-scale=1" >
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" >
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" > </script >
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" > </script >
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" > </script >
          
        </style>
   
</head>
<body>

    <table style="width:80%">
        <tr>

            <th colspan="6">
                <h3 align="center"><b>Order Details</b></h3>
            </th>
            </tr>
            <tr>
                <td colspan="6">
            <fieldset>
                <div class="form-element-row">
                    @Html.Label("Vendor")
                    @Html.TextBoxFor(m => m.Vendor)
                </div>
                <div class="form-element-row">
                    @Html.Label("Supplier")
                    @Html.TextBoxFor(m => m.Supplier)
                </div>
                <div class="form-element-row">
                    @Html.Label("Order Date")
                    @Html.TextBoxFor(m => m.Order_Date)
                </div>
            </fieldset>
            </td>
                </tr>
         <tr>
            <th>Product*</th>
            <th>Description</th>
            <th>Price</th>
            <th>Quantity*</th>
            <th>Amount</th>
            <th>Delete</th>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#"><u>delete</u></a></td>

        </tr>
        <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#"><u>delete</u></a></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#"><u>delete</u></a></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#"><u>delete</u></a></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#"><u>delete</u></a></td>
        </tr>
        <tr>
            <td colspan="6">

                <div align="center">
                    <p><b>Total Order Value </b><input type="text" name="total" /></p>
                    <button type="button" class="btn btn-primary">Save</button>
                    <input type="button" value="Refresh" class="btn btn-primary" onclick="location.href='@Url.Action("index","OrderDetails")'" />
                    <input type="button" value="Cancel" class="btn btn-primary" onclick="location.href='@Url.Action("ListOfOrder","ListOfOrder")'" />



                </div>
            </td>
        </tr>
    </table>
</body>
</html>