Sales Warrior/Models/Vendor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales_Warrior.Models
{
    public class Vendor
    {
        public string Vendor_Id { get; set; }
        public string Vendor_Name { get; set; }
        public string Address { get; set; }
        public int Tax_Registration { get; set; }
        public string Email_ID { get; set; }
        public string Phone_Number { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public int ID { get; set; }
        public List<SelectListItem> vendor { get; set; }
    }
}

Sales Warrior/Controllers/ListOfOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Sales_Warrior;
using Sales_Warrior.Models;
namespace Sales_Warrior.Controllers
{
    public class ListOfOrderController : Controller
    {
        Sales_WarriorEntities ord = new Sales_WarriorEntities();
        [HttpGet]
        public ActionResult ListOfOrder()
        {
            var Vendor_Name = (from p in ord.Orders
                               join vn in ord.Vendors
                               on p.Vendor_Id equals vn.Vendor_Id
                               select new
                               {
                                   vn.Vendor_Name,
                                   vn.Vendor_Id
                               }).ToList();
            var vlist = new SelectList(Vendor_Name.ToList(), "Vendor_Id", "Vendor_Name");
            ViewBag.Vendor_Name = vlist;
            return View();
        }
        //[HttpPost]
        //public ActionResult search()
        //{
        //    return View();
        //}

        [HttpGet]
        public ActionResult FillCity(string Vendor_Id)
        {
            var Suppliers = (from s in ord.Suppliers
                             join o in ord.Orders
                             on s.Sup_Id equals o.Sup_Id
                             where o.Vendor_Id == Vendor_Id
                             select new
                             {
                                 s.Sup_Id,
                                 s.Sup_Name
                             }).ToList().Distinct();
            ViewBag.Supplier = Suppliers.ToList();
            return Json(Suppliers.AsEnumerable(), JsonRequestBehavior.AllowGet);
            //    return this.Json(Suppliers, JsonRequestBehavior.AllowGet);
            //    var list = new SelectList(Suppliers.ToList(), "Sup_Id", "Sup_Name");
            //ViewBag.Supplier = list;
            ////var cities = db.Cities.Where(c => c.StateId == state);
            ////return View();
            //return Json(ViewBag.Supplier, JsonRequestBehavior.AllowGet);

        }

    }
}
    

Sales Warrior/Controllers/ProductSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales_Warrior.Controllers
{
    public class ProductSearchController : Controller
    {
        Sales_WarriorEntities obj = new Sales_WarriorEntities();
        // GET: ProductSearch
        public ActionResult Productsearch()
        {
            return View(obj.Product_Search(""));
        }
        [HttpPost]
        public ActionResult Productsearch(string ProductName)
        {

            return View(obj.Product_Search(ProductName));
        }
    }
}

Sales Warrior/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales_Warrior.Controllers
{
    public class VendorController : Controller
    {
        // GET: Vendor
        public ActionResult Vendor()
        {
            return View();
        }
        public ActionResult ListOfOrder()
        {
            return View();
        }
    }
}

Sales Warrior/Views/Vendor/ListOfOrder.cshtml
@model IEnumerable<Sales_Warrior.Product>
@{
    ViewBag.Title = "Productsearch";
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            padding: 10px;
        }
    </style>
    <title>SupplierDetails</title>
</head>
<body>
    @using (Html.BeginForm("Productsearch", "ProductSearch", FormMethod.Post))
    {
        <table align="center">
            <tr><td colspan="6"><h4 align="center">Vendors</h4></td></tr>
            <tr><th colspan="6">Product:@Html.TextBox("ProductName")  <input type="submit" value="Search" class="btn btn-primary" /></th></tr>
            <tr>
                <th>Product_Id</th>
                <th>Product_Name</th>
                <th>Min_Order_Quantity</th>
                <th>Lead_For_Delivery</th>
                <th>Status</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td> @item.Prod_Id </td>
                    <td> @item.Prod_Name</td>
                    <td>@item.Min_Order_Qunatity</td>
                    <td> @item.Lead_For_Delivery</td>
                    <td> @item.Status</td>
                </tr>
            }
            <tr>
                <td colspan="6" align="center">
                    <input type="button" value="Refresh" class="btn btn-primary" onclick="location.href='@Url.Action("Productsearch", "Productsearch")'" />
                    <input type="button" value="Cancel" class="btn btn-primary" onclick="location.href='@Url.Action("Menu", "Menu")'" />

                </td>
            </tr>

        </table>

    }

</body>
</html>

Sales Warrior/Views/Vendor/Vendor.cshtml
<!DOCTYPE html>
<html>
<head>
    <h1 align="center">Sales Warrior</h1>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>


    <script type="text/javascript">
        function preventBack() {
            window.history.forward();
            }
            setTimeout("preventBack()", 0);
            window.onunload = function () {
                null
            };
        </script>


</head>
<body>
    <style>

        #pic {
            max-height: 40px;
            max-width: 40px;
            width: 40px;
            height: 40px;
        }
    </style>

    <nav class="navbar navbar-expand-sm bg-light">
        <ul class="navbar-nav">

            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    <h5> MyOrder</h5>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">MyOrder</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    <h5>Suppliers</h5>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Link 1</a>
                    <a class="dropdown-item" href="#">Link 2</a>
                    <a class="dropdown-item" href="#">Link 3</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    <h5>Products</h5>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Link 1</a>
                    <a class="dropdown-item" href="#">Link 2</a>
                    <a class="dropdown-item" href="#">Link 3</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;
                    Welcome @TempData["Name"]
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    <img src="~/Images/pic.png" id="pic" />
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Update Profile</a>
                    <a href="/Home/Home" class="dropdown-item">Log Out</a>
                </div>
            </li>
        </ul>
    </nav>
    <br>
</body>
</html>